version: "3.8"

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command:
      - rasa
      - run
      - --enable-api
      - --cors
      - "*"

  action_server:
    image: rasa/rasa-sdk:3.0.0
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command:
      - rasa
      - run
      - actions
      - --cors
      - "*"